stages:
    - build
    - e2e
    - deploy

e2e tests:
    stage: e2e
    image: mcr.microsoft.com/playwright:v1.22.0-focal
    script:
        - npm ci
        - npx playwright test

artifacts:
        when: always
        paths:
            - playwright-report/
            - test-results/
            - results.xml
        reports:
            junit: results.xml